<content>
	<museum>
		<info><![CDATA[The SPAM Museum is an amazing museum about the entire family of SPAM products. That seems obvious, right? But it is so much more. It is the center of the SPAM universe. A place beyond description. A place where more than learning occurs. A place where magic happens.]]></info>
		<events><![CDATA[There's always something exciting going on at the SPAM Museum. Like daily tours. Exciting visitors from strange places. Disruptions in the space-time continuum. Sun, clouds, and rain. If you missed the Grand Opening in June 2002, you missed a lot. Stay tuned.]]></events>
		<hours><![CDATA[We would love to keep the SPAM Museum open 24 hours a day. SPAM research is critical to mankind, and emergency situations can arise. But unfortunately, we need to get some sleep once in a while.<br><br>OPEN: 10-5 MON-SAT & 12-4 SUN<br>CLOSED: Mondays (Labor Day-April 30),<br>New Year's Day, Easter Day, Thanksgiving Day,<br>Christmas Eve and Christmas Day. <br><br>FREE!<br>Yes, you read it right, NO ADMISSION FEE.<br><br>]]></hours>
	</museum>
	<mobile>
		<info><![CDATA[They‘re the three largest SPAM cans in the world. <br><br>Instead of containing pure pork shoulder and ham, however, each of the three cans is actually a vehicle used to prepare sample sizes of SPAMBURGER hamburgers. The large replicas of a SPAM can are crossing the United States to enable people to become more familiar with the great taste of SPAM Classic and SPAM Oven Roasted Turkey. <br><br>The first SPAMMOBILE vehicle, shaped from a trolley car chassis, was unveiled in March 2001. Since then, it has been appearing at retail stores during weekdays and concerts, festivals, sporting events and other venues on weekends. <br><br>A second SPAMMOBILE vehicle rolled out in mid-April 2002 and the third unit went into service at the end of that month. <br><br>Each SPAMMOBILE vehicle is designed to resemble a blue and yellow can of SPAM. The sides of the vehicle portray the front of a can of SPAM and the front of the unit displays two eyes and a smile to give the vehicle a friendly demeanor. <br><br>]]></info>
		<schedule url="http://www.spammobile.com/" />
		<facts><![CDATA[Each vehicle is approximately 28 feet long, eight feet wide and 10 feet high. Inside, electric sandwich grills are used to prepare miniature SPAMBURGER hamburgers. <br><br>Approximately 500,000 SPAMBURGER hamburgers will be served during the year by each SPAMMOBILE vehicle, or about 1.5 million sandwiches for all three vehicles. The three vehicles will travel a combined total of about 120,000 miles, operating year-round to attend nearly 675 events each year. Each vehicle is supported by a field manager/driver and a crew of trained SPAMbassadors.<br><br>Sometimes, after you get through the sample line, you get a free SPAM gift! <br> <br>I bet if a SPAMMOBILE got going fast enough it could jump the Grand Canyon.<br><br>The SPAMMOBILE is designed to look like a can of SPAM. It‘s true. <br><br>The SPAMMOBILE is blue. So plan your wardrobe in advance. Let‘s not clash, OK?<br> <br>]]></facts>
	</mobile>
</content>